// ── Client boundary ────────────────────────────────────────────────────────────
export { createDbClient, createServiceDbClient, withClinicContext, toJson } from './client.js'
export type { Sql, TxSql } from './client.js'

// ── Types ──────────────────────────────────────────────────────────────────────
export type {
  ClinicPlan,
  ClinicStatus,
  Channel,
  Clinic,
  ClinicUser,
  ClinicUserStatus,
  Role,
  Permission,
  RolePermission,
  UserRole,
  AuditEvent,
  Patient,
  PatientStatus,
  PatientContact,
  Conversation,
  ConversationStatus,
  ConversationMessage,
  ContentType,
  MessageRole,
  ConversationTag,
  ConversationTagLink,
  InternalNote,
  ChannelAccount,
  ChannelAccountStatus,
  WebhookEvent,
  MessageDeliveryEvent,
  DeliveryStatus,
  Service,
  Provider,
  ProviderAvailability,
  Appointment,
  AppointmentStatus,
  AppointmentEvent,
  AppointmentEventType,
  IaProfile,
  IaRule,
  IaRuleType,
  KnowledgeDocument,
  DocumentType,
  DocumentStatus,
  KnowledgeChunk,
  AiUsageEvent,
  NotificationEvent,
  NotificationType,
  NotificationStatus,
  ErrorReview,
  ErrorReviewStatus,
  FeatureFlag,
  DevSeedRun,
  SeedRunStatus,
} from './types/index.js'

// ── Repository factories ───────────────────────────────────────────────────────
export {
  createClinicsRepository,
  createPatientsRepository,
  createConversationsRepository,
  createMessagesRepository,
  createAppointmentsRepository,
  createKnowledgeRepository,
  createAuditRepository,
} from './repositories/index.js'

export type {
  ClinicsRepository,
  CreateClinicInput,
  UpdateClinicInput,
  PatientsRepository,
  CreatePatientInput,
  UpdatePatientInput,
  CreatePatientContactInput,
  ConversationsRepository,
  CreateConversationInput,
  UpdateConversationInput,
  CreateTagInput,
  CreateNoteInput,
  MessagesRepository,
  CreateMessageInput,
  AppointmentsRepository,
  CreateAppointmentInput,
  UpdateAppointmentInput,
  CreateProviderInput,
  CreateServiceInput,
  KnowledgeRepository,
  CreateDocumentInput,
  CreateChunkInput,
  CreateIaProfileInput,
  UpdateIaProfileInput,
  CreateIaRuleInput,
  AuditRepository,
  CreateAuditEventInput,
  AuditEventFilter,
} from './repositories/index.js'
